import streamlit as st
import google.generativeai as genai

API_KEY = st.secrets.get("GOOGLE_API_KEY")

if not API_KEY:
    raise Exception("GOOGLE_API_KEY not found in Streamlit Secrets.")

genai.configure(api_key=API_KEY)

model = genai.GenerativeModel("gemini-2.5-flash")


def get_gemini_response(prompt):
    try:
        response = model.generate_content(prompt)

        # Debugging
        print("Response:", response)

        if hasattr(response, "text") and response.text:
            return response.text

        return "No response generated by Gemini."

    except Exception as e:
        print("Gemini Error:", e)
        return f"Gemini Error: {e}"
